[font]
size = 14.0

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
opacity = 1

[window.dimensions]
columns = 120
lines = 50

[window.padding]
x = 2
y = 2
