[[index]]
name = "public"
url = "https://anexus3.kbc.be:6087/nexus/repository/public-python-group/simple"
default = true

[[index]]
name = "dbu"
url = "https://anexus3.kbc.be:6087/nexus/repository/dbu-python/simple"

[[index]]
name = "pypi"
url = "https://pypi.org/simple"

[pip]
index-url = "https://anexus3.kbc.be:6087/nexus/repository/eab-python/simple"
extra-index-url = [
  "https://anexus3.kbc.be:6087/nexus/repository/public-python-group/simple"
]

