git:
  # Array of pagers. Each entry has the following format:
  #
  #   # Value of the --color arg in the git diff command. Some pagers want
  #   # this to be set to 'always' and some want it set to 'never'
  #   colorArg: "always"
  #
  #   # e.g.
  #   # diff-so-fancy
  #   # delta --dark --paging=never
  #   # ydiff -p cat -s --wrap --width={{columnWidth}}
  #   pager: ""
  #
  #   # e.g. 'difft --color=always'
  #   externalDiffCommand: ""
  #
  #   # If true, Lazygit will use git's `diff.external` config for paging.
  #   # The advantage over `externalDiffCommand` is that this can be
  #   # configured per file type in .gitattributes; see
  #   # https://git-scm.com/docs/gitattributes#_defining_an_external_diff_driver.
  #   useExternalDiffGitConfig: false
  #
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
  # for more information.
  pagers:
    - pager: delta --dark --paging=never
    - externalDiffCommand: difft --color=always
  # Command used when displaying the current branch git log in the main window
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --oneline --pretty=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)' {{branchName}} --
  # Commands used to display git log of all branches in the main window, they will
  # be cycled in order of appearance (array of strings)
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --oneline --pretty=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)'
customCommands:
  # retrieved from: https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium#conventional-commit
  - key: "<c-v>"
    context: "global"
    description: "Create new conventional commit"
    prompts:
      - type: "menu"
        key: "Type"
        title: "Type of change"
        options:
          - name: "build"
            description: "Changes that affect the build system or external dependencies"
            value: "build"
          - name: "feat"
            description: "A new feature"
            value: "feat"
          - name: "fix"
            description: "A bug fix"
            value: "fix"
          - name: "chore"
            description: "Other changes that don't modify src or test files"
            value: "chore"
          - name: "ci"
            description: "Changes to CI configuration files and scripts"
            value: "ci"
          - name: "docs"
            description: "Documentation only changes"
            value: "docs"
          - name: "perf"
            description: "A code change that improves performance"
            value: "perf"
          - name: "refactor"
            description: "A code change that neither fixes a bug nor adds a feature"
            value: "refactor"
          - name: "revert"
            description: "Reverts a previous commit"
            value: "revert"
          - name: "style"
            description: "Changes that do not affect the meaning of the code"
            value: "style"
          - name: "test"
            description: "Adding missing tests or correcting existing tests"
            value: "test"
      - type: "input"
        title: "Scope"
        key: "Scope"
        initialValue: ""
      - type: "menu"
        key: "Breaking"
        title: "Breaking change"
        options:
          - name: "no"
            value: ""
          - name: "yes"
            value: "!"
      - type: "input"
        title: "message"
        key: "Message"
        initialValue: ""
      - type: "confirm"
        key: "Confirm"
        title: "Commit"
        body: "Are you sure you want to commit?"
    command: "git commit --message '{{.Form.Type}}{{ if .Form.Scope }}({{ .Form.Scope }}){{ end }}{{.Form.Breaking}}: {{.Form.Message}}'"
    loadingText: "Creating conventional commit..."
