require("user.keymaps")
require("user.plugins")
require("user.telescope")
require("user.treesitter")
require("user.colorscheme")
require("user.alpha")
require("user.lualine")
require("user.bufferline")
require("user.comment")
require("user.cmp")
require("user.lsp")
require("user.gitsigns")
require("user.nvim-tree")
require("user.toggleterm")
require("user.options")
require("user.nvim-lsp-installer")
require("user.nvim-lspconfig")
-- require("user.nvim-dap")

