#!/usr/bin/bash

# ----------------------------------------
### ALIASES
# ----------------------------------------

# kitty sessions
alias km='kitty --session monitor.conf &'
alias ko='kitty --session ops.conf &'

# TZ
export TZ='Europe/Sofia'
