#!/bin/sh

# alias sz='source ~/.zshrc'

# alias j='z'
# alias f='zi'
# alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
# alias nvimrc='nvim ~/.config/nvim/'
#

# -----------------------------------------------
# ------------------ Searching ------------------
# -----------------------------------------------

# grep
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# find
# alias fd='fdfind'

# fzf
alias fzfp='fzf --preview "bat --style=numbers --color=always {}"'

# -----------------------------------------------
# -----------------------------------------------
# -----------------------------------------------

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# -----------------------------------------------
# -----------------------------------------------
# -----------------------------------------------
alias m="git checkout master"
alias s="git checkout stable"

alias lss='logo-ls'
alias ls='lsd'

alias brave="sh /opt/brave.com/brave/brave-browser"
