#!/bin/sh

# alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# -----------------------------------------------
# ------------------ Searching ------------------
# -----------------------------------------------

# grep
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# find
# alias fd='fdfind'

# fzf
alias fzfp='fzf --preview "bat --style=numbers --color=always {}"'

# -----------------------------------------------
# ------------------- System --------------------
# -----------------------------------------------

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# -----------------------------------------------
# --------------- Applications ------------------
# -----------------------------------------------

###################################
# git
###################################

alias ga='git add --verbose'
alias gaa='git add --all'
alias gb='git branch'
alias gc='git commit'
alias gcm='git commit -m'
alias gcon='git config --list'
alias gch='git checkout'
alias gd='git diff'
alias gf='git fetch'
alias gp='git push origin $(current_branch)'
alias gpl='git pull origin $(current_branch)'
alias gl='git log'
alias gm='git merge'
alias gr='git reset --hard'
alias gst='git status'
alias gsh='git stash'

alias lg='lazygit'

###################################
# listing
###################################

alias lss='logo-ls'
alias ls='lsd'

###################################
# other
###################################

alias brave="sh /opt/brave.com/brave/brave-browser"
