# vim:fileencoding=utf-8:foldmethod=marker

font_family      MesloLGS Nerd Font Mono Regular
bold_font        MesloLGS Nerd Font Mono Bold
italic_font      MesloLGS Nerd Font Mono Italic
bold_italic_font MesloLGS Nerd Font Mono Bold Italic

font_size 16.0

#: Scrollback

scrollback_lines 20000
scrollbar scrolled

#: Mouse

copy_on_select yes

#: Terminal bell

enable_audio_bell no
visual_bell_duration 0.5

#: Window layout

enabled_layouts Tall, *
window_border_width 2pt

#: Tab bar

tab_bar_style powerline
tab_powerline_style slanted

#: Color scheme

background_image /home/hristo/config_repo/kitty/blue.png
background_image_layout scaled
background_tint 0.9

#: Advanced

allow_remote_control socket-only
listen_on unix:/tmp/kitty
startup_session ~/.config/kitty/op-session
shell_integration enabled

#: Keyboard shortcuts

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten /home/hristo/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py

# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output

map ctrl+left neighboring_window left
map shift+right move_window right
map ctrl+down neighboring_window down
map shift+up move_window up
map ctrl+right neighboring_window right
map shift+left move_window left
map ctrl+up neighboring_window up
map shift+down move_window down

#: Tab management

#: Next tab

map alt+right next_tab
# map shift+cmd+]     next_tab
# map ctrl+tab        next_tab

#: Previous tab

map alt+left previous_tab
# map shift+cmd+[    previous_tab
# map ctrl+shift+tab previous_tab

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

#: New tab

# map kitty_mod+t new_tab
map ctrl+shift+t new_tab_with_cwd

#: Close tab

# map kitty_mod+q close_tab
# map cmd+w       close_tab
map ctrl+w close_tab

#: Close OS window

# map shift+cmd+w close_os_window

#: Move tab forward

# map kitty_mod+. move_tab_forward
map ctrl+shift+page_up move_tab_backward

#: Move tab backward

# map kitty_mod+, move_tab_backward
map ctrl+shift+page_down move_tab_forward

#: Set tab title

# map kitty_mod+alt+t set_tab_title
map shift+alt+r     set_tab_title

#: Layout management

#: Next layout

map ctrl+shift+l next_layout

#: You can also create shortcuts to switch to specific layouts::

#:     map ctrl+alt+t goto_layout tall
#:     map ctrl+alt+s goto_layout stack

#: Similarly, to switch back to the previous layout::

#:     map ctrl+alt+p last_used_layout

#:     map ctrl+alt+z toggle_layout stack

#: Miscellaneous

#: Reload kitty.conf

# map kitty_mod+f5 load_config_file
map ctrl+shift+c   load_config_file

#: Quit kitty

map ctrl+shift+q quit
